-- =========================================================
-- ĐỒ ÁN MÔN HỌC: FOOTBALL CLUB MANAGEMENT
-- HỆ QUẢN TRỊ CƠ SỞ DỮ LIỆU: ORACLE DB
-- =========================================================

-- 1. Tạo bảng Cầu thủ (Players)
CREATE TABLE Players (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName VARCHAR2(100) NOT NULL,
    position VARCHAR2(10) NOT NULL,
    jerseyNumber NUMBER(3) NOT NULL,
    healthStatus VARCHAR2(50) DEFAULT 'Fit',
    ovr NUMBER(3) DEFAULT 50,
    goals NUMBER(4) DEFAULT 0,
    mvp NUMBER(4) DEFAULT 0
);

-- 2. Thêm dữ liệu mẫu (Dummy Data) để test App
INSERT INTO Players (fullName, position, jerseyNumber, healthStatus, ovr, goals, mvp) 
VALUES ('Lionel Messi', 'FW', 10, 'Fit', 94, 15, 8);

INSERT INTO Players (fullName, position, jerseyNumber, healthStatus, ovr, goals, mvp) 
VALUES ('Kevin De Bruyne', 'MF', 17, 'Fit', 91, 5, 12);

INSERT INTO Players (fullName, position, jerseyNumber, healthStatus, ovr, goals, mvp) 
VALUES ('Virgil van Dijk', 'DF', 4, 'Injured', 89, 2, 4);

INSERT INTO Players (fullName, position, jerseyNumber, healthStatus, ovr, goals, mvp) 
VALUES ('Alisson Becker', 'GK', 1, 'Fit', 89, 0, 5);

COMMIT;

-- 3. Tạo Trigger tự động cập nhật OVR (Ví dụ nâng cao ăn điểm CSDL)
-- Nếu ghi được nhiều bàn thắng hoặc MVP thì tự động tăng OVR.
CREATE OR REPLACE TRIGGER trg_UpdateOVR
BEFORE UPDATE ON Players
FOR EACH ROW
BEGIN
    IF :NEW.goals > :OLD.goals THEN
        :NEW.ovr := :NEW.ovr + 1;
    END IF;
END;
/
