-- Football Club Management - Oracle schema/migration
-- This script is non-destructive: it creates missing objects and upgrades the
-- original camelCase Players table without dropping existing rows.

SET DEFINE OFF;

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'PLAYERS';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE players (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name VARCHAR2(100) NOT NULL,
                position VARCHAR2(2) NOT NULL,
                jersey_number NUMBER(3) NOT NULL,
                health_status VARCHAR2(20) DEFAULT ''Fit'' NOT NULL,
                ovr NUMBER(3) DEFAULT 70 NOT NULL,
                matches NUMBER(7) DEFAULT 0 NOT NULL,
                goals NUMBER(7) DEFAULT 0 NOT NULL,
                assists NUMBER(7) DEFAULT 0 NOT NULL,
                mvp NUMBER(7) DEFAULT 0 NOT NULL,
                club VARCHAR2(100) DEFAULT ''Tự do'' NOT NULL,
                pac NUMBER(3) DEFAULT 70 NOT NULL,
                sho NUMBER(3) DEFAULT 70 NOT NULL,
                pas NUMBER(3) DEFAULT 70 NOT NULL,
                dri NUMBER(3) DEFAULT 70 NOT NULL,
                def NUMBER(3) DEFAULT 70 NOT NULL,
                phy NUMBER(3) DEFAULT 70 NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            )';
    END IF;
END;
/

-- Upgrade column names from the first version of the assignment schema.
DECLARE
    old_count NUMBER;
    new_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO old_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'FULLNAME';
    SELECT COUNT(*) INTO new_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'FULL_NAME';
    IF old_count = 1 AND new_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE players RENAME COLUMN fullName TO full_name';
    END IF;

    SELECT COUNT(*) INTO old_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'JERSEYNUMBER';
    SELECT COUNT(*) INTO new_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'JERSEY_NUMBER';
    IF old_count = 1 AND new_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE players RENAME COLUMN jerseyNumber TO jersey_number';
    END IF;

    SELECT COUNT(*) INTO old_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'HEALTHSTATUS';
    SELECT COUNT(*) INTO new_count FROM user_tab_columns WHERE table_name = 'PLAYERS' AND column_name = 'HEALTH_STATUS';
    IF old_count = 1 AND new_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE players RENAME COLUMN healthStatus TO health_status';
    END IF;
END;
/

DECLARE
    PROCEDURE add_column_if_missing(column_name_value VARCHAR2, definition_value VARCHAR2) IS
        column_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO column_count
        FROM user_tab_columns
        WHERE table_name = 'PLAYERS' AND column_name = UPPER(column_name_value);
        IF column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE players ADD (' || definition_value || ')';
        END IF;
    END;
BEGIN
    add_column_if_missing('MATCHES', 'matches NUMBER(7) DEFAULT 0 NOT NULL');
    add_column_if_missing('ASSISTS', 'assists NUMBER(7) DEFAULT 0 NOT NULL');
    add_column_if_missing('CLUB', 'club VARCHAR2(100) DEFAULT ''Tự do'' NOT NULL');
    add_column_if_missing('PAC', 'pac NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('SHO', 'sho NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('PAS', 'pas NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('DRI', 'dri NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('DEF', 'def NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('PHY', 'phy NUMBER(3) DEFAULT 70 NOT NULL');
    add_column_if_missing('CREATED_AT', 'created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL');
    add_column_if_missing('UPDATED_AT', 'updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL');
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'APP_USERS';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE app_users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(32) NOT NULL,
                password_hash VARCHAR2(255) NOT NULL,
                role VARCHAR2(20) DEFAULT ''manager'' NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                CONSTRAINT uq_app_users_username UNIQUE (username),
                CONSTRAINT ck_app_users_role CHECK (role IN (''manager'', ''viewer''))
            )';
    END IF;
END;
/

DECLARE
    index_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO index_count FROM user_indexes WHERE index_name = 'UQ_PLAYERS_JERSEY_NUMBER';
    IF index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_players_jersey_number ON players (jersey_number)';
    END IF;
END;
/

DECLARE
    table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_count FROM user_tables WHERE table_name = 'SCHEMA_MIGRATIONS';
    IF table_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE schema_migrations (
                version VARCHAR2(64) PRIMARY KEY,
                applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            )';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_players_ovr_and_timestamp
BEFORE INSERT OR UPDATE ON players
FOR EACH ROW
BEGIN
    IF INSERTING
       OR :NEW.pac <> :OLD.pac OR :NEW.sho <> :OLD.sho OR :NEW.pas <> :OLD.pas
       OR :NEW.dri <> :OLD.dri OR :NEW.def <> :OLD.def OR :NEW.phy <> :OLD.phy THEN
        :NEW.ovr := TRUNC((:NEW.pac + :NEW.sho + :NEW.pas + :NEW.dri + :NEW.def + :NEW.phy) / 6);
    END IF;
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Idempotent sample roster for a clean database.
MERGE INTO players target
USING (
    SELECT 'Lionel Messi' full_name, 'FW' position, 10 jersey_number, 92 pac, 95 sho, 91 pas, 96 dri, 38 def, 65 phy FROM dual
    UNION ALL
    SELECT 'Kevin De Bruyne', 'MF', 17, 76, 89, 94, 88, 65, 78 FROM dual
    UNION ALL
    SELECT 'Virgil van Dijk', 'DF', 4, 78, 60, 71, 72, 92, 90 FROM dual
    UNION ALL
    SELECT 'Alisson Becker', 'GK', 1, 65, 40, 70, 60, 45, 82 FROM dual
) source
ON (target.jersey_number = source.jersey_number)
WHEN NOT MATCHED THEN INSERT (
    full_name, position, jersey_number, health_status, matches, goals, assists, mvp,
    club, pac, sho, pas, dri, def, phy
) VALUES (
    source.full_name, source.position, source.jersey_number, 'Fit', 0, 0, 0, 0,
    'FC Manager', source.pac, source.sho, source.pas, source.dri, source.def, source.phy
);

MERGE INTO schema_migrations target
USING (SELECT '20260901_backend_hardening' version FROM dual) source
ON (target.version = source.version)
WHEN NOT MATCHED THEN INSERT (version) VALUES (source.version);

COMMIT;
