-- ==============================================================================
-- TRƯỜNG ĐẠI HỌC CÔNG NGHỆ ĐÔNG Á - VIỆN ĐÀO TẠO VÀ HỢP TÁC QUỐC TẾ
-- ĐỀ THI KẾT THÚC HỌC PHẦN: ORACLE DATABASE MANAGEMENT SYSTEM
-- MÃ BỘ ĐỀ: A2 - ĐỀ TÀI: TOPIC 3 - SPORTS CLUB MANAGEMENT SOFTWARE
-- FILE: 01_SCHEMA_AND_CONSTRAINTS.sql
-- MÔ TẢ: TẠO TOÀN BỘ CẤU TRÚC BẢNG, KHÓA CHÍNH, KHÓA NGOẠI VÀ RÀNG BUỘC TOÀN VẸN
-- ==============================================================================

-- Xóa bảng cũ nếu tồn tại (theo thứ tự quan hệ khóa ngoại)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
             ('FINANCES', 'PLAYER_TRAINING', 'TRAINING_SESSIONS', 'MATCH_EVENTS', 'MATCHES', 'PLAYERS', 'CLUBS', 'APP_USERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- 1. BẢNG APP_USERS: Quản lý người dùng hệ thống và phân quyền truy cập
CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(32) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'manager' NOT NULL,
    full_name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('admin', 'manager', 'coach', 'staff'))
);

-- 2. BẢNG CLUBS: Thông tin các câu lạc bộ thể thao trong hệ thống
CREATE TABLE clubs (
    club_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name VARCHAR2(100) NOT NULL UNIQUE,
    short_name VARCHAR2(10) NOT NULL,
    founded_year NUMBER(4) DEFAULT 2020 NOT NULL,
    stadium_name VARCHAR2(100) DEFAULT 'Sân vận động Trung tâm',
    stadium_capacity NUMBER(6) DEFAULT 10000,
    head_coach VARCHAR2(100),
    city VARCHAR2(100) DEFAULT 'Hà Nội',
    budget NUMBER(15, 2) DEFAULT 1000000000.00 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_founded_year CHECK (founded_year >= 1800 AND founded_year <= 2100),
    CONSTRAINT chk_budget_positive CHECK (budget >= 0)
);

-- 3. BẢNG PLAYERS: Quản lý thông tin hồ sơ và chỉ số năng lực cầu thủ (FIFA Standard)
CREATE TABLE players (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER DEFAULT 1 NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    position VARCHAR2(3) NOT NULL,
    jersey_number NUMBER(3) NOT NULL,
    health_status VARCHAR2(20) DEFAULT 'Fit' NOT NULL,
    ovr NUMBER(3) DEFAULT 75 NOT NULL,
    matches NUMBER(7) DEFAULT 0 NOT NULL,
    goals NUMBER(7) DEFAULT 0 NOT NULL,
    assists NUMBER(7) DEFAULT 0 NOT NULL,
    mvp NUMBER(7) DEFAULT 0 NOT NULL,
    pac NUMBER(3) DEFAULT 70 NOT NULL,
    sho NUMBER(3) DEFAULT 70 NOT NULL,
    pas NUMBER(3) DEFAULT 70 NOT NULL,
    dri NUMBER(3) DEFAULT 70 NOT NULL,
    def NUMBER(3) DEFAULT 70 NOT NULL,
    phy NUMBER(3) DEFAULT 70 NOT NULL,
    salary NUMBER(12, 2) DEFAULT 15000000.00 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_players_club FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
    CONSTRAINT chk_position CHECK (position IN ('GK', 'DF', 'MF', 'FW', 'ST', 'CB', 'LB', 'RB', 'CM', 'CAM', 'CDM', 'RW', 'LW')),
    CONSTRAINT chk_jersey_number CHECK (jersey_number BETWEEN 1 AND 99),
    CONSTRAINT chk_health_status CHECK (health_status IN ('Fit', 'Injured', 'Suspended', 'Resting')),
    CONSTRAINT chk_ovr_range CHECK (ovr BETWEEN 40 AND 99),
    CONSTRAINT chk_stats_pac CHECK (pac BETWEEN 1 AND 99),
    CONSTRAINT chk_stats_sho CHECK (sho BETWEEN 1 AND 99),
    CONSTRAINT chk_stats_pas CHECK (pas BETWEEN 1 AND 99),
    CONSTRAINT chk_stats_dri CHECK (dri BETWEEN 1 AND 99),
    CONSTRAINT chk_stats_def CHECK (def BETWEEN 1 AND 99),
    CONSTRAINT chk_stats_phy CHECK (phy BETWEEN 1 AND 99),
    CONSTRAINT chk_salary_positive CHECK (salary >= 0)
);

-- 4. BẢNG MATCHES: Quản lý lịch thi đấu và kết quả các trận đấu
CREATE TABLE matches (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER DEFAULT 1 NOT NULL,
    match_date DATE NOT NULL,
    opponent_team VARCHAR2(100) NOT NULL,
    venue VARCHAR2(100) DEFAULT 'Sân nhà',
    match_type VARCHAR2(50) DEFAULT 'League' NOT NULL,
    home_score NUMBER(3) DEFAULT 0 NOT NULL,
    away_score NUMBER(3) DEFAULT 0 NOT NULL,
    referee_name VARCHAR2(100),
    attendance NUMBER(6) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_matches_club FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
    CONSTRAINT chk_match_type CHECK (match_type IN ('Friendly', 'League', 'Cup', 'Tournament')),
    CONSTRAINT chk_home_score CHECK (home_score >= 0),
    CONSTRAINT chk_away_score CHECK (away_score >= 0)
);

-- 5. BẢNG MATCH_EVENTS: Ghi nhận chi tiết diễn biến trận đấu (Bàn thắng, kiến tạo, thẻ phạt)
CREATE TABLE match_events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    event_type VARCHAR2(20) NOT NULL,
    minute_occurred NUMBER(3) NOT NULL,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_event_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_event_type CHECK (event_type IN ('Goal', 'Assist', 'Yellow Card', 'Red Card', 'Substitution', 'Penalty Saved')),
    CONSTRAINT chk_minute_occurred CHECK (minute_occurred BETWEEN 1 AND 120)
);

-- 6. BẢNG TRAINING_SESSIONS: Quản lý các buổi tập huấn chuyên môn
CREATE TABLE training_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER DEFAULT 1 NOT NULL,
    session_date DATE NOT NULL,
    focus_area VARCHAR2(100) NOT NULL,
    duration_minutes NUMBER(4) DEFAULT 90 NOT NULL,
    location VARCHAR2(100) DEFAULT 'Trung tâm huấn luyện',
    coach_in_charge VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_training_club FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
    CONSTRAINT chk_duration_minutes CHECK (duration_minutes BETWEEN 15 AND 360)
);

-- 7. BẢNG PLAYER_TRAINING: Ghi nhận điểm danh và đánh giá năng lực qua buổi tập
CREATE TABLE player_training (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    performance_rating NUMBER(3, 1) DEFAULT 7.0 NOT NULL,
    attendance_status VARCHAR2(20) DEFAULT 'Present' NOT NULL,
    coach_notes VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pt_session FOREIGN KEY (session_id) REFERENCES training_sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_pt_rating CHECK (performance_rating BETWEEN 1.0 AND 10.0),
    CONSTRAINT chk_pt_attendance CHECK (attendance_status IN ('Present', 'Absent', 'Excused', 'Late'))
);

-- 8. BẢNG FINANCES: Quản lý tài chính thu chi của câu lạc bộ
CREATE TABLE finances (
    trans_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER DEFAULT 1 NOT NULL,
    trans_type VARCHAR2(10) NOT NULL,
    category VARCHAR2(50) NOT NULL,
    amount NUMBER(15, 2) NOT NULL,
    trans_date DATE DEFAULT SYSDATE NOT NULL,
    description VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_finances_club FOREIGN KEY (club_id) REFERENCES clubs(club_id) ON DELETE CASCADE,
    CONSTRAINT chk_trans_type CHECK (trans_type IN ('Revenue', 'Expense')),
    CONSTRAINT chk_trans_amount CHECK (amount > 0)
);

-- TẠO CHỈ MỤC (INDEXES) TỐI ƯU HÓA TRUY VẤN
CREATE INDEX idx_players_club ON players(club_id);
CREATE INDEX idx_players_name ON players(LOWER(full_name));
CREATE BITMAP INDEX idx_players_pos ON players(position);
CREATE BITMAP INDEX idx_players_health ON players(health_status);
CREATE INDEX idx_matches_date ON matches(match_date);
CREATE INDEX idx_events_match ON match_events(match_id);
CREATE INDEX idx_events_player ON match_events(player_id);
CREATE BITMAP INDEX idx_events_type ON match_events(event_type);
CREATE INDEX idx_pt_session ON player_training(session_id);
CREATE INDEX idx_pt_player ON player_training(player_id);
CREATE INDEX idx_finances_date ON finances(trans_date);

COMMIT;
PROMPT CSDL CLB Thể thao đã được tạo thành công với 8 bảng và đầy đủ ràng buộc toàn vẹn!
