-- ==============================================================================
-- TRƯỜNG ĐẠI HỌC CÔNG NGHỆ ĐÔNG Á - VIỆN ĐÀO TẠO VÀ HỢP TÁC QUỐC TẾ
-- ĐỀ THI KẾT THÚC HỌC PHẦN: ORACLE DATABASE MANAGEMENT SYSTEM
-- FILE: 06_ADVANCED_FEATURES.sql
-- MÔ TẢ: CÁC TÍNH NĂNG NÂNG CAO (ADVANCED ORACLE FEATURES - ĐẠT ĐIỂM XUẤT SẮC / ĐIỂM CỘNG)
-- ==============================================================================

-- 1. FUNCTION-BASED INDEX (Tối ưu tìm kiếm không phân biệt hoa thường)
CREATE INDEX idx_players_lower_name ON players(LOWER(full_name));

-- 2. BITMAP INDEX TRÊN CỘT CÓ ĐỘ PHÂN BIỆT THẤP (Low Cardinality)
CREATE BITMAP INDEX idx_players_pos_bitmap ON players(position);
CREATE BITMAP INDEX idx_events_type_bitmap ON match_events(event_type);

-- 3. MÔ PHỎNG PHÂN VÙNG DỮ LIỆU (TABLE PARTITIONING THEO RANGE NĂM)
-- Tính năng chứng minh năng lực thiết kế CSDL lớn (Enterprise Big Data)
/*
CREATE TABLE matches_partitioned (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    club_id NUMBER NOT NULL,
    match_date DATE NOT NULL,
    opponent_team VARCHAR2(100) NOT NULL,
    home_score NUMBER(3) DEFAULT 0,
    away_score NUMBER(3) DEFAULT 0
)
PARTITION BY RANGE (match_date) (
    PARTITION p_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD')),
    PARTITION p_2026 VALUES LESS THAN (TO_DATE('2027-01-01', 'YYYY-MM-DD')),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);
*/

-- 4. FLASHBACK QUERY (Khôi phục dữ liệu thời điểm quá khứ mà không cần restore backup)
-- Xem dữ liệu bảng players cách đây 15 phút (Yêu cầu bật UNDO_RETENTION)
/*
SELECT * FROM players AS OF TIMESTAMP (SYSTIMESTAMP - INTERVAL '15' MINUTE);
*/

PROMPT Tính năng nâng cao đã được cấu hình và sẵn sàng trình bày!
