SET ECHO ON;
SET DEFINE OFF;
SET SERVEROUTPUT ON;

-- ==============================================================================
-- BƯỚC 1: DỌN DẸP AN TOÀN TRƯỚC KHI TẠO (TRÁNH LỖI ORA-00955 VÀ ORA-00942)
-- ==============================================================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
             ('PLAYER_TRAINING', 'TRAINING_SESSIONS', 'MATCH_EVENTS', 'MATCHES', 'PLAYERS', 'APP_USERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ==============================================================================
-- BƯỚC 2: TẠO CẤU TRÚC 6 BẢNG CHUẨN 3NF (TABLES VÀ CONSTRAINTS)
-- ==============================================================================

-- 1. Bảng tài khoản người dùng
CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(32) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'manager' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('admin', 'manager', 'coach', 'staff'))
);

-- 2. Bảng cầu thủ bóng đá (Bảng trung tâm hệ thống)
CREATE TABLE players (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    position VARCHAR2(2) NOT NULL,
    jersey_number NUMBER(3) NOT NULL,
    health_status VARCHAR2(20) DEFAULT 'Fit' NOT NULL,
    ovr NUMBER(3) DEFAULT 70 NOT NULL,
    matches NUMBER(7) DEFAULT 0 NOT NULL,
    goals NUMBER(7) DEFAULT 0 NOT NULL,
    assists NUMBER(7) DEFAULT 0 NOT NULL,
    mvp NUMBER(7) DEFAULT 0 NOT NULL,
    club VARCHAR2(100) DEFAULT 'Tự do' NOT NULL,
    pac NUMBER(3) DEFAULT 70 NOT NULL,
    sho NUMBER(3) DEFAULT 70 NOT NULL,
    pas NUMBER(3) DEFAULT 70 NOT NULL,
    dri NUMBER(3) DEFAULT 70 NOT NULL,
    def NUMBER(3) DEFAULT 70 NOT NULL,
    phy NUMBER(3) DEFAULT 70 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_player_position CHECK (position IN ('FW', 'MF', 'DF', 'GK')),
    CONSTRAINT chk_player_jersey CHECK (jersey_number BETWEEN 1 AND 99),
    CONSTRAINT chk_player_health CHECK (health_status IN ('Fit', 'Injured', 'Suspended')),
    CONSTRAINT chk_player_ovr CHECK (ovr BETWEEN 1 AND 99),
    CONSTRAINT chk_player_pac CHECK (pac BETWEEN 0 AND 100),
    CONSTRAINT chk_player_sho CHECK (sho BETWEEN 0 AND 100),
    CONSTRAINT chk_player_pas CHECK (pas BETWEEN 0 AND 100),
    CONSTRAINT chk_player_dri CHECK (dri BETWEEN 0 AND 100),
    CONSTRAINT chk_player_def CHECK (def BETWEEN 0 AND 100),
    CONSTRAINT chk_player_phy CHECK (phy BETWEEN 0 AND 100)
);

-- 3. Bảng lịch thi đấu và kết quả trận đấu
CREATE TABLE matches (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_date DATE NOT NULL,
    opponent_team VARCHAR2(100) NOT NULL,
    venue VARCHAR2(100) DEFAULT 'Sân nhà',
    match_type VARCHAR2(50) DEFAULT 'Friendly',
    home_score NUMBER(3) DEFAULT 0,
    away_score NUMBER(3) DEFAULT 0,
    CONSTRAINT chk_match_type CHECK (match_type IN ('Friendly', 'League', 'Cup')),
    CONSTRAINT chk_home_score CHECK (home_score >= 0),
    CONSTRAINT chk_away_score CHECK (away_score >= 0)
);

-- 4. Bảng chi tiết sự kiện trận đấu (Bàn thắng, kiến tạo, thẻ phạt)
CREATE TABLE match_events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    event_type VARCHAR2(20) NOT NULL,
    minute NUMBER(3) NOT NULL,
    CONSTRAINT fk_event_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_event_type CHECK (event_type IN ('Goal', 'Assist', 'Yellow Card', 'Red Card', 'MVP')),
    CONSTRAINT chk_minute CHECK (minute BETWEEN 1 AND 120)
);

-- 5. Bảng buổi tập luyện chuyên môn
CREATE TABLE training_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE NOT NULL,
    focus_area VARCHAR2(100) NOT NULL,
    duration_minutes NUMBER(3) DEFAULT 90 NOT NULL,
    CONSTRAINT chk_training_duration CHECK (duration_minutes > 0)
);

-- 6. Bảng điểm danh và đánh giá buổi tập của cầu thủ
CREATE TABLE player_training (
    session_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    performance_rating NUMBER(2) DEFAULT 5,
    CONSTRAINT pk_player_training PRIMARY KEY (session_id, player_id),
    CONSTRAINT fk_pt_session FOREIGN KEY (session_id) REFERENCES training_sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_training_rating CHECK (performance_rating BETWEEN 1 AND 10)
);

-- ==============================================================================
-- BƯỚC 3: NẠP DỮ LIỆU MẪU ĐẦY ĐỦ VÀO 6 BẢNG (INSERT VÀ COMMIT)
-- ==============================================================================

-- 3.1 Nạp tài khoản người dùng
INSERT INTO app_users (username, password_hash, role) VALUES ('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');
INSERT INTO app_users (username, password_hash, role) VALUES ('coach_bang', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'coach');
INSERT INTO app_users (username, password_hash, role) VALUES ('manager_kien', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'manager');

-- 3.2 Nạp 10 cầu thủ tiêu biểu (6 từ 'FC Đông Á', 4 từ 'Tự do')
INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Quang Hải', 'MF', 19, 'Fit', 84, 18, 7, 11, 4, 'FC Đông Á', 82, 85, 88, 86, 60, 72);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Tiến Linh', 'FW', 22, 'Fit', 83, 20, 14, 4, 5, 'FC Đông Á', 81, 86, 75, 78, 45, 84);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Đoàn Văn Hậu', 'DF', 5, 'Injured', 81, 12, 2, 5, 1, 'FC Đông Á', 84, 70, 78, 79, 82, 86);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Đặng Văn Lâm', 'GK', 1, 'Fit', 82, 19, 0, 0, 3, 'FC Đông Á', 50, 40, 72, 45, 85, 84);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Hoàng Đức', 'MF', 28, 'Fit', 85, 21, 6, 12, 6, 'FC Đông Á', 80, 81, 89, 87, 74, 82);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Quế Ngọc Hải', 'DF', 3, 'Fit', 82, 17, 1, 2, 2, 'FC Đông Á', 72, 60, 76, 70, 85, 85);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Phạm Tuấn Hải', 'FW', 10, 'Fit', 83, 20, 11, 6, 3, 'Tự do', 86, 84, 79, 83, 55, 80);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Vũ Văn Thanh', 'DF', 17, 'Fit', 80, 16, 3, 4, 1, 'Tự do', 85, 73, 76, 78, 77, 81);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Tuấn Anh', 'MF', 11, 'Fit', 79, 14, 1, 5, 1, 'Tự do', 74, 72, 85, 84, 70, 68);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Bùi Tiến Dũng', 'DF', 4, 'Fit', 80, 15, 1, 1, 1, 'Tự do', 74, 55, 71, 68, 83, 81);

-- 3.3 Nạp 5 trận đấu trong tháng 9 và tháng 10 năm 2026
INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-05', 'YYYY-MM-DD'), 'Hải Phòng FC', 'Sân nhà Lạch Tray', 'League', 3, 1);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-12', 'YYYY-MM-DD'), 'Nam Định FC', 'Sân khách Thiên Trường', 'League', 2, 2);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-19', 'YYYY-MM-DD'), 'Hà Nội FC', 'Sân nhà Hàng Đẫy', 'League', 1, 0);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-26', 'YYYY-MM-DD'), 'Bình Dương FC', 'Sân khách Gò Đậu', 'Cup', 4, 2);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-10-03', 'YYYY-MM-DD'), 'SHB Đà Nẵng', 'Sân nhà Hòa Xuân', 'Friendly', 2, 0);

-- 3.4 Nạp 10 sự kiện trận đấu (Bàn thắng, kiến tạo, thẻ)
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 1, 'Goal', 24);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 2, 'Goal', 65);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 5, 'Assist', 24);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 3, 'Yellow Card', 78);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 2, 'Goal', 45);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 7, 'Goal', 88);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 1, 'Assist', 45);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (3, 7, 'Goal', 52);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (4, 2, 'Goal', 15);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (4, 2, 'Goal', 70);

-- 3.5 Nạp các buổi tập luyện
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-02', 'YYYY-MM-DD'), 'Chiến thuật phản công nhanh (Tactical)', 90);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-09', 'YYYY-MM-DD'), 'Thể lực và bứt tốc (Fitness Training)', 120);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-16', 'YYYY-MM-DD'), 'Kỹ thuật dứt điểm vòng cấm (Finishing)', 90);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-23', 'YYYY-MM-DD'), 'Bóng bổng và phòng ngự khu vực (Defending)', 90);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TRUNC(SYSDATE), 'Thể lực duy trì phong độ toàn đội', 90);

-- 3.6 Nạp kết quả đánh giá tập luyện
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 1, 9);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 2, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 5, 10);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 2, 9);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 7, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 8, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (3, 2, 10);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (3, 7, 9);

COMMIT;
PROMPT >>> DA TAO BANG VA NAP DU LIEU MAU THANH CONG! <<<

-- ==============================================================================
-- BƯỚC 4: LẬP TRÌNH ĐỐI TƯỢNG PL/SQL (VIEWS, TRIGGERS, FUNCTIONS, PROCEDURES, PACKAGE)
-- ==============================================================================

-- 4.1 VIEW: Danh sách cầu thủ khỏe mạnh sẵn sàng thi đấu
CREATE OR REPLACE VIEW view_active_squad AS
SELECT id, full_name, position, jersey_number, ovr, goals, assists, health_status
FROM players
WHERE health_status = 'Fit'
WITH READ ONLY;

-- 4.2 VIEW: Bảng xếp hạng ghi bàn (Top Scorers)
CREATE OR REPLACE VIEW v_top_scorers AS
SELECT id AS player_id, full_name, position, club, goals, assists, matches
FROM players
WHERE goals > 0
ORDER BY goals DESC, assists DESC;

-- 4.3 VIEW: Bảng tổng kết kết quả thi đấu (Match Summary)
CREATE OR REPLACE VIEW v_match_summary AS
SELECT match_id, match_date, opponent_team, venue, match_type,
       home_score || ' - ' || away_score AS final_score,
       CASE 
           WHEN home_score > away_score THEN 'Thắng (Win)'
           WHEN home_score < away_score THEN 'Thua (Loss)'
           ELSE 'Hòa (Draw)'
       END AS result
FROM matches;

-- 4.4 STANDALONE FUNCTION: Đánh giá phong độ cầu thủ (Có dùng IF-ELSIF-ELSE)
CREATE OR REPLACE FUNCTION get_player_form(p_player_id IN NUMBER) RETURN VARCHAR2 IS
    v_goals NUMBER := 0;
    v_assists NUMBER := 0;
    v_rating VARCHAR2(50);
BEGIN
    SELECT goals, assists INTO v_goals, v_assists FROM players WHERE id = p_player_id;
    IF (v_goals + v_assists) >= 10 THEN
        v_rating := 'Phong độ xuất sắc (World Class)';
    ELSIF (v_goals + v_assists) >= 5 THEN
        v_rating := 'Phong độ ổn định (Good)';
    ELSE
        v_rating := 'Cần cải thiện (Normal)';
    END IF;
    RETURN v_rating;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Không tìm thấy cầu thủ';
END get_player_form;
/

-- 4.5 STANDALONE PROCEDURE: Báo cáo kết quả tập luyện (Có dùng FOR LOOP)
CREATE OR REPLACE PROCEDURE generate_training_report IS
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- BÁO CÁO ĐÁNH GIÁ TẬP LUYỆN TOÀN ĐỘI ---');
    FOR rec IN (
        SELECT p.full_name, ts.focus_area, pt.performance_rating
        FROM player_training pt
        JOIN players p ON pt.player_id = p.id
        JOIN training_sessions ts ON pt.session_id = ts.session_id
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Cầu thủ: ' || rec.full_name || ' | Bài tập: ' || rec.focus_area || ' | Điểm: ' || rec.performance_rating);
    END LOOP;
END generate_training_report;
/

-- 4.6 TRIGGER 1: Tự động cập nhật bàn thắng, kiến tạo, MVP vào hồ sơ cầu thủ
CREATE OR REPLACE TRIGGER trg_after_match_event
AFTER INSERT ON match_events
FOR EACH ROW
BEGIN
    IF :NEW.event_type = 'Goal' THEN
        UPDATE players SET goals = goals + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    ELSIF :NEW.event_type = 'Assist' THEN
        UPDATE players SET assists = assists + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    ELSIF :NEW.event_type = 'MVP' THEN
        UPDATE players SET mvp = mvp + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    END IF;
END;
/

-- 4.7 TRIGGER 2: Tự động cập nhật thời gian updated_at trước khi sửa cầu thủ
CREATE OR REPLACE TRIGGER trg_update_timestamp
BEFORE UPDATE ON players
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 4.8 PACKAGE SPECIFICATION: Khai báo Package quản trị đội bóng FC Manager
CREATE OR REPLACE PACKAGE pkg_fc_manager IS
    FUNCTION get_top_scorer RETURN VARCHAR2;
    PROCEDURE evaluate_squad_fitness;
    PROCEDURE simulate_training_camp(p_duration_days IN NUMBER);
END pkg_fc_manager;
/

-- 4.9 PACKAGE BODY: Hiện thực Package (Có dùng IF, FOR LOOP, WHILE LOOP)
CREATE OR REPLACE PACKAGE BODY pkg_fc_manager IS

    -- Function: Tìm vua phá lưới của đội (Dùng IF và FETCH FIRST)
    FUNCTION get_top_scorer RETURN VARCHAR2 IS
        v_name VARCHAR2(100);
        v_goals NUMBER;
    BEGIN
        SELECT full_name, goals INTO v_name, v_goals 
        FROM players 
        ORDER BY goals DESC 
        FETCH FIRST 1 ROWS ONLY;
        
        IF v_goals = 0 THEN
            RETURN 'Chưa có bàn thắng nào';
        ELSE
            RETURN v_name || ' (' || v_goals || ' bàn thắng)';
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'Danh sách cầu thủ rỗng';
    END get_top_scorer;

    -- Procedure 1: Đánh giá phân hạng thể lực cầu thủ (Dùng Cursor FOR LOOP VÀ IF-ELSIF)
    PROCEDURE evaluate_squad_fitness IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('====================================================');
        DBMS_OUTPUT.PUT_LINE('       BÁO CÁO ĐÁNH GIÁ THỂ LỰC VÀ ĐỘI HÌNH CLB     ');
        DBMS_OUTPUT.PUT_LINE('====================================================');
        FOR player_rec IN (SELECT full_name, ovr, health_status FROM players ORDER BY ovr DESC) LOOP
            IF player_rec.health_status != 'Fit' THEN
                DBMS_OUTPUT.PUT_LINE('[-] ' || RPAD(player_rec.full_name, 22) || ': ĐANG CHẤN THƯƠNG (Cần chăm sóc y tế)');
            ELSIF player_rec.ovr >= 84 THEN
                DBMS_OUTPUT.PUT_LINE('[*] ' || RPAD(player_rec.full_name, 22) || ': NGÔI SAO ĐẲNG CẤP (Star Player)');
            ELSIF player_rec.ovr >= 80 THEN
                DBMS_OUTPUT.PUT_LINE('[+] ' || RPAD(player_rec.full_name, 22) || ': TRỤ CỘT CHÍNH THỨC (Key Starter)');
            ELSE
                DBMS_OUTPUT.PUT_LINE('[ ] ' || RPAD(player_rec.full_name, 22) || ': CẦU THỦ DỰ BỊ CHIẾN LƯỢC');
            END IF;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('====================================================');
    END evaluate_squad_fitness;

    -- Procedure 2: Mô phỏng chuỗi ngày tập huấn chuyên sâu (Dùng WHILE LOOP)
    PROCEDURE simulate_training_camp(p_duration_days IN NUMBER) IS
        v_day NUMBER := 1;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Mô phỏng đợt tập huấn ' || p_duration_days || ' ngày:');
        WHILE v_day <= p_duration_days LOOP
            INSERT INTO training_sessions(session_date, focus_area, duration_minutes)
            VALUES (SYSDATE + v_day, 'Tập huấn chuyên sâu ngày ' || v_day, 120);
            v_day := v_day + 1;
        END LOOP;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hoàn thành tạo lịch tập huấn thành công!');
    END simulate_training_camp;

END pkg_fc_manager;
/

-- ==============================================================================
-- BƯỚC 5: TỰ ĐỘNG CHẠY KIỂM THỬ THỦ TỤC PL/SQL (CHO BẠN CHỤP ẢNH MINH HỌA)
-- ==============================================================================
PROMPT ====================================================================
PROMPT KET QUA CHAY THU TUC PL/SQL (CHUP ANH SCRIPT OUTPUT DUOI DAY):
PROMPT ====================================================================
BEGIN
    pkg_fc_manager.evaluate_squad_fitness;
END;
/

SELECT pkg_fc_manager.get_top_scorer AS vua_pha_luoi FROM dual;
