-- ==============================================================================
-- TRƯỜNG ĐẠI HỌC CÔNG NGHỆ ĐÔNG Á - VIỆN ĐÀO TẠO VÀ HỢP TÁC QUỐC TẾ
-- ĐỀ THI KẾT THÚC HỌC PHẦN: ORACLE DATABASE MANAGEMENT SYSTEM
-- MÃ BỘ ĐỀ: A2 - ĐỀ TÀI: TOPIC 3 - SPORTS CLUB MANAGEMENT SOFTWARE
-- FILE: ORACLE_SQL_DEVELOPER_FULL.sql
-- MÔ TẢ: TOÀN BỘ SCRIPT CHUẨN ĐỂ CHẠY TRÊN ORACLE SQL DEVELOPER
--        (BAO GỒM: TẠO BẢNG, NẠP DỮ LIỆU, PL/SQL, 20 QUERY, PHÂN QUYỀN)
-- ==============================================================================

SET ECHO ON;
SET SERVEROUTPUT ON;

-- ==============================================================================
-- BƯỚC 0: DỌN DẸP AN TOÀN TRƯỚC KHI TẠO (TRÁNH LỖI ORA-00955 VÀ ORA-00942)
-- ==============================================================================
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN 
             ('PLAYER_TRAINING', 'TRAINING_SESSIONS', 'MATCH_EVENTS', 'MATCHES', 'PLAYERS', 'APP_USERS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ==============================================================================
-- PHẦN 1: TẠO CẤU TRÚC 6 BẢNG CSDL (TABLES & CONSTRAINTS)
-- ==============================================================================

-- 1. Bảng tài khoản người dùng
CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(32) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'manager' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('admin', 'manager', 'coach', 'staff'))
);

-- 2. Bảng cầu thủ bóng đá (Bảng trung tâm hệ thống)
CREATE TABLE players (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    position VARCHAR2(2) NOT NULL,
    jersey_number NUMBER(3) NOT NULL,
    health_status VARCHAR2(20) DEFAULT 'Fit' NOT NULL,
    ovr NUMBER(3) DEFAULT 70 NOT NULL,
    matches NUMBER(7) DEFAULT 0 NOT NULL,
    goals NUMBER(7) DEFAULT 0 NOT NULL,
    assists NUMBER(7) DEFAULT 0 NOT NULL,
    mvp NUMBER(7) DEFAULT 0 NOT NULL,
    club VARCHAR2(100) DEFAULT 'Tự do' NOT NULL,
    pac NUMBER(3) DEFAULT 70 NOT NULL,
    sho NUMBER(3) DEFAULT 70 NOT NULL,
    pas NUMBER(3) DEFAULT 70 NOT NULL,
    dri NUMBER(3) DEFAULT 70 NOT NULL,
    def NUMBER(3) DEFAULT 70 NOT NULL,
    phy NUMBER(3) DEFAULT 70 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_player_position CHECK (position IN ('FW', 'MF', 'DF', 'GK')),
    CONSTRAINT chk_player_jersey CHECK (jersey_number BETWEEN 1 AND 99),
    CONSTRAINT chk_player_health CHECK (health_status IN ('Fit', 'Injured', 'Suspended')),
    CONSTRAINT chk_player_ovr CHECK (ovr BETWEEN 1 AND 99),
    CONSTRAINT chk_player_pac CHECK (pac BETWEEN 0 AND 100),
    CONSTRAINT chk_player_sho CHECK (sho BETWEEN 0 AND 100),
    CONSTRAINT chk_player_pas CHECK (pas BETWEEN 0 AND 100),
    CONSTRAINT chk_player_dri CHECK (dri BETWEEN 0 AND 100),
    CONSTRAINT chk_player_def CHECK (def BETWEEN 0 AND 100),
    CONSTRAINT chk_player_phy CHECK (phy BETWEEN 0 AND 100)
);

-- 3. Bảng lịch thi đấu và kết quả trận đấu
CREATE TABLE matches (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_date DATE NOT NULL,
    opponent_team VARCHAR2(100) NOT NULL,
    venue VARCHAR2(100) DEFAULT 'Sân nhà',
    match_type VARCHAR2(50) DEFAULT 'Friendly',
    home_score NUMBER(3) DEFAULT 0,
    away_score NUMBER(3) DEFAULT 0,
    CONSTRAINT chk_match_type CHECK (match_type IN ('Friendly', 'League', 'Cup')),
    CONSTRAINT chk_home_score CHECK (home_score >= 0),
    CONSTRAINT chk_away_score CHECK (away_score >= 0)
);

-- 4. Bảng chi tiết sự kiện trận đấu (Bàn thắng, kiến tạo, thẻ phạt)
CREATE TABLE match_events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    event_type VARCHAR2(20) NOT NULL,
    minute NUMBER(3) NOT NULL,
    CONSTRAINT fk_event_match FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_event_type CHECK (event_type IN ('Goal', 'Assist', 'Yellow Card', 'Red Card', 'MVP')),
    CONSTRAINT chk_minute CHECK (minute BETWEEN 1 AND 120)
);

-- 5. Bảng buổi tập luyện chuyên môn
CREATE TABLE training_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE NOT NULL,
    focus_area VARCHAR2(100) NOT NULL,
    duration_minutes NUMBER(3) DEFAULT 90 NOT NULL,
    CONSTRAINT chk_training_duration CHECK (duration_minutes > 0)
);

-- 6. Bảng điểm danh và đánh giá buổi tập của cầu thủ
CREATE TABLE player_training (
    session_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    performance_rating NUMBER(2) DEFAULT 5,
    CONSTRAINT pk_player_training PRIMARY KEY (session_id, player_id),
    CONSTRAINT fk_pt_session FOREIGN KEY (session_id) REFERENCES training_sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE,
    CONSTRAINT chk_training_rating CHECK (performance_rating BETWEEN 1 AND 10)
);

-- ==============================================================================
-- PHẦN 2: NẠP DỮ LIỆU MẪU ĐẦY ĐỦ (INSERT SAMPLE DATA)
-- ==============================================================================

-- 1. Nạp tài khoản ban huấn luyện
INSERT INTO app_users (username, password_hash, role) VALUES ('admin', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');
INSERT INTO app_users (username, password_hash, role) VALUES ('coach_bang', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'coach');
INSERT INTO app_users (username, password_hash, role) VALUES ('manager_kien', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'manager');

-- 2. Nạp danh sách cầu thủ bóng đá tiêu biểu
INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Quang Hải', 'MF', 19, 'Fit', 84, 18, 7, 11, 4, 'FC Đông Á', 82, 85, 88, 86, 60, 72);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Tiến Linh', 'FW', 22, 'Fit', 83, 20, 14, 4, 5, 'FC Đông Á', 81, 86, 75, 78, 45, 84);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Đoàn Văn Hậu', 'DF', 5, 'Injured', 81, 12, 2, 5, 1, 'FC Đông Á', 84, 70, 78, 79, 82, 86);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Đặng Văn Lâm', 'GK', 1, 'Fit', 82, 19, 0, 0, 3, 'FC Đông Á', 50, 40, 72, 45, 85, 84);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Hoàng Đức', 'MF', 28, 'Fit', 85, 21, 6, 12, 6, 'FC Đông Á', 80, 81, 89, 87, 74, 82);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Quế Ngọc Hải', 'DF', 3, 'Fit', 82, 17, 1, 2, 2, 'FC Đông Á', 72, 60, 76, 70, 85, 85);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Phạm Tuấn Hải', 'FW', 10, 'Fit', 83, 20, 11, 6, 3, 'Free Agent', 86, 84, 79, 83, 55, 80);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Vũ Văn Thanh', 'DF', 17, 'Fit', 80, 16, 3, 4, 1, 'Free Agent', 85, 73, 76, 78, 77, 81);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Nguyễn Tuấn Anh', 'MF', 11, 'Fit', 79, 14, 1, 5, 1, 'Free Agent', 74, 72, 85, 84, 70, 68);

INSERT INTO players (full_name, position, jersey_number, health_status, ovr, matches, goals, assists, mvp, club, pac, sho, pas, dri, def, phy)
VALUES ('Bùi Tiến Dũng', 'DF', 4, 'Fit', 80, 15, 1, 1, 1, 'Free Agent', 74, 55, 71, 68, 83, 81);

-- 3. Nạp lịch thi đấu trong tháng 9/2026
INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-05', 'YYYY-MM-DD'), 'Hải Phòng FC', 'Sân nhà Lạch Tray', 'League', 3, 1);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-12', 'YYYY-MM-DD'), 'Nam Định FC', 'Sân khách Thiên Trường', 'League', 2, 2);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-19', 'YYYY-MM-DD'), 'Hà Nội FC', 'Sân nhà Hàng Đẫy', 'League', 1, 0);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-09-26', 'YYYY-MM-DD'), 'Bình Dương FC', 'Sân khách Gò Đậu', 'Cup', 4, 2);

INSERT INTO matches (match_date, opponent_team, venue, match_type, home_score, away_score)
VALUES (TO_DATE('2026-10-03', 'YYYY-MM-DD'), 'SHB Đà Nẵng', 'Sân nhà Hòa Xuân', 'Friendly', 2, 0);

-- 4. Nạp sự kiện trận đấu (Bàn thắng, kiến tạo, thẻ phạt)
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 1, 'Goal', 24);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 2, 'Goal', 65);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 5, 'Assist', 24);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (1, 3, 'Yellow Card', 78);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 2, 'Goal', 45);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 7, 'Goal', 88);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (2, 1, 'Assist', 45);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (3, 7, 'Goal', 52);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (4, 2, 'Goal', 15);
INSERT INTO match_events (match_id, player_id, event_type, minute) VALUES (4, 2, 'Goal', 70);

-- 5. Nạp buổi tập luyện
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-02', 'YYYY-MM-DD'), 'Chiến thuật phản công nhanh (Tactical)', 90);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-09', 'YYYY-MM-DD'), 'Thể lực và bứt tốc (Fitness Training)', 120);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-16', 'YYYY-MM-DD'), 'Kỹ thuật dứt điểm vòng cấm (Finishing)', 90);
INSERT INTO training_sessions (session_date, focus_area, duration_minutes) VALUES (TO_DATE('2026-09-23', 'YYYY-MM-DD'), 'Bóng bổng và phòng ngự khu vực (Defending)', 90);

-- 6. Nạp điểm danh tập luyện
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 1, 9);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 2, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (1, 5, 10);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 2, 9);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 7, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (2, 8, 8);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (3, 2, 10);
INSERT INTO player_training (session_id, player_id, performance_rating) VALUES (3, 7, 9);

COMMIT;
PROMPT >>> DA NAP THANH CONG DU LIEU MAU VAO 6 BANG! <<<

-- ==============================================================================
-- PHẦN 3: LẬP TRÌNH ĐỐI TƯỢNG PL/SQL (VIEWS, TRIGGERS, PACKAGE)
-- ==============================================================================

-- 3.1 VIEW: Danh sách cầu thủ khỏe mạnh sẵn sàng thi đấu
CREATE OR REPLACE VIEW view_active_squad AS
SELECT id, full_name, position, jersey_number, ovr, goals, assists, health_status
FROM players
WHERE health_status = 'Fit'
WITH READ ONLY;

-- 3.2 TRIGGER: Tự động cộng dồn bàn thắng/kiến tạo khi có sự kiện trận đấu (Có dùng IF)
CREATE OR REPLACE TRIGGER trg_after_match_event
AFTER INSERT ON match_events
FOR EACH ROW
BEGIN
    IF :NEW.event_type = 'Goal' THEN
        UPDATE players SET goals = goals + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    ELSIF :NEW.event_type = 'Assist' THEN
        UPDATE players SET assists = assists + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    ELSIF :NEW.event_type = 'MVP' THEN
        UPDATE players SET mvp = mvp + 1, updated_at = CURRENT_TIMESTAMP WHERE id = :NEW.player_id;
    END IF;
END;
/

-- 3.3 TRIGGER: Tự động cập nhật thời gian updated_at trước khi sửa thông tin
CREATE OR REPLACE TRIGGER trg_update_timestamp
BEFORE UPDATE ON players
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- 3.4 PACKAGE: Quản trị nghiệp vụ đội bóng (Có dùng IF-THEN-ELSE, FOR LOOP, WHILE LOOP)
CREATE OR REPLACE PACKAGE pkg_fc_manager IS
    FUNCTION get_top_scorer RETURN VARCHAR2;
    PROCEDURE evaluate_squad_fitness;
    PROCEDURE simulate_training_camp(p_duration_days IN NUMBER);
END pkg_fc_manager;
/

CREATE OR REPLACE PACKAGE BODY pkg_fc_manager IS

    -- Function: Tìm cầu thủ ghi nhiều bàn nhất đội
    FUNCTION get_top_scorer RETURN VARCHAR2 IS
        v_name VARCHAR2(100);
        v_goals NUMBER;
    BEGIN
        SELECT full_name, goals INTO v_name, v_goals 
        FROM players 
        ORDER BY goals DESC 
        FETCH FIRST 1 ROWS ONLY;
        
        IF v_goals = 0 THEN
            RETURN 'Chưa có bàn thắng nào';
        ELSE
            RETURN v_name || ' (' || v_goals || ' bàn thắng)';
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 'Danh sách rỗng';
    END get_top_scorer;

    -- Procedure 1: Đánh giá phân hạng cầu thủ bằng Cursor FOR LOOP và IF-ELSE
    PROCEDURE evaluate_squad_fitness IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('=== BÁO CÁO PHÂN HẠNG CẦU THỦ TOÀN ĐỘI ===');
        FOR player_rec IN (SELECT full_name, ovr, health_status FROM players) LOOP
            IF player_rec.health_status != 'Fit' THEN
                DBMS_OUTPUT.PUT_LINE('[-] ' || player_rec.full_name || ': Đang chấn thương (Cần chăm sóc y tế)');
            ELSIF player_rec.ovr >= 84 THEN
                DBMS_OUTPUT.PUT_LINE('[*] ' || player_rec.full_name || ': Ngôi sao đẳng cấp (Star Player)');
            ELSIF player_rec.ovr >= 80 THEN
                DBMS_OUTPUT.PUT_LINE('[+] ' || player_rec.full_name || ': Trụ cột chính thức (Key Starter)');
            ELSE
                DBMS_OUTPUT.PUT_LINE('[ ] ' || player_rec.full_name || ': Cầu thủ dự bị chiến lược');
            END IF;
        END LOOP;
    END evaluate_squad_fitness;

    -- Procedure 2: Mô phỏng chuỗi ngày tập huấn chuyên sâu bằng WHILE LOOP
    PROCEDURE simulate_training_camp(p_duration_days IN NUMBER) IS
        v_day NUMBER := 1;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Mô phỏng đợt tập huấn ' || p_duration_days || ' ngày:');
        WHILE v_day <= p_duration_days LOOP
            INSERT INTO training_sessions(session_date, focus_area, duration_minutes)
            VALUES (SYSDATE + v_day, 'Tập huấn chuyên sâu ngày ' || v_day, 120);
            v_day := v_day + 1;
        END LOOP;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('Hoàn thành tạo lịch tập huấn thành công!');
    END simulate_training_camp;

END pkg_fc_manager;
/

-- Kiểm tra chạy thử thủ tục PL/SQL
EXEC pkg_fc_manager.evaluate_squad_fitness;
SELECT pkg_fc_manager.get_top_scorer AS vua_pha_luoi FROM dual;

-- ==============================================================================
-- PHẦN 4: 20 CÂU TRUY VẤN SQL ĐẠT BAREM CHẤM ĐIỂM (4 NHÓM)
-- ==============================================================================

-- A. BASIC QUERIES (5 CÂU CƠ BẢN)
PROMPT --- 1. Lấy danh sách cầu thủ tự do ---
SELECT full_name, position, ovr FROM players WHERE club = 'Free Agent' ORDER BY ovr DESC;

PROMPT --- 2. Lịch thi đấu trong tháng 9 năm 2026 ---
SELECT match_id, opponent_team, venue, match_date FROM matches 
WHERE match_date >= TO_DATE('2026-09-01', 'YYYY-MM-DD') AND match_date < TO_DATE('2026-10-01', 'YYYY-MM-DD');

PROMPT --- 3. Danh sách tài khoản quản trị hệ thống ---
SELECT id, username, role, created_at FROM app_users WHERE role = 'admin';

PROMPT --- 4. Các buổi tập luyện thời lượng từ 90 phút trở lên ---
SELECT session_id, session_date, focus_area, duration_minutes FROM training_sessions WHERE duration_minutes >= 90;

PROMPT --- 5. Tiền đạo có tốc độ (PAC) và dứt điểm (SHO) trên 80 ---
SELECT full_name, jersey_number, pac, sho, ovr FROM players WHERE pac > 80 AND sho > 80 AND position = 'FW';

-- B. NESTED QUERIES / SUBQUERIES (5 CÂU TRUY VẤN LỒNG)
PROMPT --- 6. Cầu thủ có điểm OVR cao nhất toàn đội ---
SELECT full_name, position, ovr, club FROM players WHERE ovr = (SELECT MAX(ovr) FROM players);

PROMPT --- 7. Cầu thủ đã từng ghi bàn trong các trận đấu (dùng IN) ---
SELECT full_name, position, goals FROM players WHERE id IN (SELECT DISTINCT player_id FROM match_events WHERE event_type = 'Goal');

PROMPT --- 8. Các trận đấu mà đội ghi bàn nhiều hơn trung bình các trận ---
SELECT match_id, opponent_team, home_score FROM matches WHERE home_score > (SELECT AVG(home_score) FROM matches);

PROMPT --- 9. Cầu thủ chưa từng tham gia buổi tập nào (dùng NOT EXISTS) ---
SELECT p.id, p.full_name, p.position FROM players p WHERE NOT EXISTS (SELECT 1 FROM player_training pt WHERE pt.player_id = p.id);

PROMPT --- 10. Tài khoản quản trị được tạo sớm nhất hệ thống ---
SELECT username, role, created_at FROM app_users WHERE created_at = (SELECT MIN(created_at) FROM app_users);

-- C. GROUP BY & HAVING (5 CÂU GOM NHÓM THỐNG KÊ)
PROMPT --- 11. Đếm số lượng và tính OVR trung bình theo từng vị trí thi đấu ---
SELECT position, COUNT(*) AS so_luong, ROUND(AVG(ovr), 1) AS ovr_trung_binh FROM players GROUP BY position ORDER BY so_luong DESC;

PROMPT --- 12. Cầu thủ ghi từ 2 bàn thắng trở lên trong các sự kiện trận đấu ---
SELECT player_id, COUNT(*) AS tong_so_ban FROM match_events WHERE event_type = 'Goal' GROUP BY player_id HAVING COUNT(*) >= 2;

PROMPT --- 13. Điểm đánh giá tập luyện trung bình của từng cầu thủ ---
SELECT player_id, ROUND(AVG(performance_rating), 2) AS diem_tb_tap_luyen FROM player_training GROUP BY player_id ORDER BY diem_tb_tap_luyen DESC;

PROMPT --- 14. Thống kê số trận và tổng số bàn thắng theo loại giải đấu ---
SELECT match_type, COUNT(*) AS so_tran, SUM(home_score) AS tong_ban_thang FROM matches GROUP BY match_type;

PROMPT --- 15. Buổi tập có điểm đánh giá chất lượng trung bình từ 8.0 trở lên ---
SELECT session_id, ROUND(AVG(performance_rating), 2) AS diem_buoi_tap FROM player_training GROUP BY session_id HAVING AVG(performance_rating) >= 8.0;

-- D. AGGREGATE QUERIES (5 CÂU TÍNH TOÁN TỔNG HỢP)
PROMPT --- 16. Điểm trung bình các bộ chỉ số thể chất của toàn đội ---
SELECT ROUND(AVG(pac), 1) AS avg_pac, ROUND(AVG(sho), 1) AS avg_sho, ROUND(AVG(pas), 1) AS avg_pas, 
       ROUND(AVG(dri), 1) AS avg_dri, ROUND(AVG(def), 1) AS avg_def, ROUND(AVG(phy), 1) AS avg_phy FROM players;

PROMPT --- 17. Chỉ số OVR cao nhất, thấp nhất, trung bình và độ lệch chuẩn ---
SELECT MAX(ovr) AS ovr_cao_nhat, MIN(ovr) AS ovr_thap_nhat, ROUND(AVG(ovr), 2) AS ovr_trung_binh, ROUND(STDDEV(ovr), 2) AS do_lech_chuan FROM players;

PROMPT --- 18. Tổng số bàn thắng và hiệu số bàn thắng bại của câu lạc bộ ---
SELECT SUM(home_score) AS tong_ban_thang, SUM(away_score) AS tong_ban_thua, (SUM(home_score) - SUM(away_score)) AS hieu_so FROM matches;

PROMPT --- 19. Tổng số thẻ phạt (Thẻ vàng, thẻ đỏ) đã ghi nhận ---
SELECT COUNT(CASE WHEN event_type = 'Yellow Card' THEN 1 END) AS the_vang,
       COUNT(CASE WHEN event_type = 'Red Card' THEN 1 END) AS the_do,
       COUNT(*) AS tong_so_the FROM match_events WHERE event_type IN ('Yellow Card', 'Red Card');

PROMPT --- 20. Tổng thời lượng tập luyện trong tháng hiện tại ---
SELECT COUNT(*) AS so_buoi_tap, SUM(duration_minutes) AS tong_phut_tap, ROUND(SUM(duration_minutes)/60, 1) AS tong_gio_tap 
FROM training_sessions WHERE EXTRACT(MONTH FROM session_date) = EXTRACT(MONTH FROM SYSDATE);

-- ==============================================================================
-- PHẦN 5: PHÂN QUYỀN NGƯỜI DÙNG VÀ SAO LƯU (USER MANAGEMENT & BACKUP)
-- ==============================================================================

-- Tạo Role phân quyền cho trợ lý HLV nhập liệu
CREATE ROLE coach_data_entry;
GRANT SELECT, INSERT, UPDATE ON players TO coach_data_entry;
GRANT SELECT, INSERT ON matches TO coach_data_entry;
GRANT SELECT, INSERT ON match_events TO coach_data_entry;

-- Tạo Role tra cứu cho tuyển trạch viên (Scout)
CREATE ROLE scout_read_only;
GRANT SELECT ON players TO scout_read_only;
GRANT SELECT ON view_active_squad TO scout_read_only;

-- Tạo user và gán quyền
CREATE USER coach_bang IDENTIFIED BY CoachSecure2026;
GRANT CONNECT, RESOURCE TO coach_bang;
GRANT coach_data_entry TO coach_bang;

CREATE USER scout_kien IDENTIFIED BY ScoutSecure2026;
GRANT CONNECT TO scout_kien;
GRANT scout_read_only TO scout_kien;

PROMPT >>> HOAN THANH TOAN BO QUA TRINH THI HANH CSDL TREN ORACLE SQL DEVELOPER! <<<
